/* Generated by scripts/generate-emergency-validators.mjs. Do not edit. */
import type { IdentityAcceptedV1 } from '../contracts/generated/enterprise-security-v1/types/IdentityAcceptedV1'
import type { IdentityEmergencyActivateRequestV1 } from '../contracts/generated/enterprise-security-v1/types/IdentityEmergencyActivateRequestV1'
import type { IdentityEmergencyActivationV1 } from '../contracts/generated/enterprise-security-v1/types/IdentityEmergencyActivationV1'
import type { IdentityEmergencyEntryRequestV1 } from '../contracts/generated/enterprise-security-v1/types/IdentityEmergencyEntryRequestV1'
import type { IdentityPasskeyAssertRequestV1 } from '../contracts/generated/enterprise-security-v1/types/IdentityPasskeyAssertRequestV1'
import type { IdentityPasskeyAssertResultV1 } from '../contracts/generated/enterprise-security-v1/types/IdentityPasskeyAssertResultV1'
export interface EmergencyRequestMap {
  'identity.passkey.assert': IdentityPasskeyAssertRequestV1
  'identity.emergency.entry': IdentityEmergencyEntryRequestV1
  'identity.emergency.activate': IdentityEmergencyActivateRequestV1
}
export interface EmergencyResponseMap {
  'identity.passkey.assert': IdentityPasskeyAssertResultV1
  'identity.emergency.entry': IdentityAcceptedV1
  'identity.emergency.activate': IdentityEmergencyActivationV1
}
export const emergencyRoutes = {
  "identity.passkey.assert": {
    "operationId": "OP-IDN-007",
    "operationKey": "identity.passkey.assert",
    "binding": "default",
    "method": "POST",
    "path": "/api/auth/v1/security/identity/passkey/assert",
    "surface": "regional_identity",
    "wire": "security_json",
    "successStatus": 200,
    "securityProfile": "ceremony",
    "failureProfile": "public_ceremony",
    "maxRequestBytes": 65536,
    "maxResponseBytes": 65536,
    "idempotency": "required_header"
  },
  "identity.emergency.entry": {
    "operationId": "OP-IDN-037",
    "operationKey": "identity.emergency.entry",
    "binding": "default",
    "method": "POST",
    "path": "/api/auth/v1/security/identity/emergency/entry",
    "surface": "regional_identity",
    "wire": "security_json",
    "successStatus": 200,
    "securityProfile": "ceremony",
    "failureProfile": "public_ceremony",
    "maxRequestBytes": 65536,
    "maxResponseBytes": 65536,
    "idempotency": "required_header"
  },
  "identity.emergency.activate": {
    "operationId": "OP-IDN-038",
    "operationKey": "identity.emergency.activate",
    "binding": "default",
    "method": "POST",
    "path": "/api/auth/v1/security/identity/emergency/activate",
    "surface": "regional_identity",
    "wire": "security_json",
    "successStatus": 200,
    "securityProfile": "ceremony",
    "failureProfile": "public_ceremony",
    "maxRequestBytes": 65536,
    "maxResponseBytes": 65536,
    "idempotency": "required_header"
  }
} as const
