/* Generated by scripts/generate-scim-validators.mjs from SaaS Rust schemas and HTTP routes. Do not edit. */
import type { IdentityAcceptedV1 } from "../contracts/generated/enterprise-security-v1/types/IdentityAcceptedV1";
import type { IdentityCeremonyProgressV1 } from "../contracts/generated/enterprise-security-v1/types/IdentityCeremonyProgressV1";
import type { IdentityScimCompleteRequestV1 } from "../contracts/generated/enterprise-security-v1/types/IdentityScimCompleteRequestV1";
import type { IdentityScimEmailStartRequestV1 } from "../contracts/generated/enterprise-security-v1/types/IdentityScimEmailStartRequestV1";
import type { IdentityScimEmailVerifyRequestV1 } from "../contracts/generated/enterprise-security-v1/types/IdentityScimEmailVerifyRequestV1";
import type { IdentityScimVerifiedActivationV1 } from "../contracts/generated/enterprise-security-v1/types/IdentityScimVerifiedActivationV1";
import * as validators from "./scim-validators.generated";
export interface ScimIdentityOperations {
  "identity.scim.primary_email.start": { request: IdentityScimEmailStartRequestV1; response: IdentityAcceptedV1; };
  "identity.scim.primary_email.verify": { request: IdentityScimEmailVerifyRequestV1; response: IdentityScimVerifiedActivationV1; };
  "identity.scim.activation.complete": { request: IdentityScimCompleteRequestV1; response: IdentityCeremonyProgressV1; };
}
export const scimIdentityContracts: { readonly [K in keyof ScimIdentityOperations]: { path: string; maxRequestBytes: number; maxResponseBytes: number; request: (input: unknown) => boolean; response: (input: unknown) => boolean } } = {
  "identity.scim.primary_email.start": { path: "/api/auth/v1/security/identity/scim/primary-email/start", maxRequestBytes: 65536, maxResponseBytes: 65536, request: validators.identity_scim_primary_email_start_request, response: validators.identity_scim_primary_email_start_response },
  "identity.scim.primary_email.verify": { path: "/api/auth/v1/security/identity/scim/primary-email/verify", maxRequestBytes: 65536, maxResponseBytes: 65536, request: validators.identity_scim_primary_email_verify_request, response: validators.identity_scim_primary_email_verify_response },
  "identity.scim.activation.complete": { path: "/api/auth/v1/security/identity/scim/activation/complete", maxRequestBytes: 65536, maxResponseBytes: 65536, request: validators.identity_scim_activation_complete_request, response: validators.identity_scim_activation_complete_response },
} as const;
